version: '1.0'

services:
  frontend:
    image: node:16.3.0-alpine3.13
    ports:
      - 5173:5173
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}:/workspace
    working_dir: /workspace
    command: sh -c "npm install && npm run dev"